"use strict";

function registerEventRoutes(router, deps) {
  const { automationServer, sendError, requireSeniorAutomationWriter, cleanString, requireAutomationCreatorAccess } = deps;

  router.get("/events", requireSeniorAutomationWriter, async (req, res) => { try { return res.json(await automationServer.listEvents({ agencyId: req.auth.agencyId, query: req.query || {} })); } catch (err) { return sendError(res, err, "AUTOMATION_EVENTS_FAILED"); } });
  router.post("/events", (_req, res) => res.status(410).json({
    ok: false,
    code: "LEGACY_AUTOMATION_EVENT_WRITER_DISABLED",
    error: "Business audit events are generated by the P15 backend control plane.",
  }));
  router.get("/activity", async (req, res) => { try { const creatorId = cleanString(req.query?.creatorId || req.query?.accountId, 100); if (!creatorId) return res.status(400).json({ ok: false, code: "CREATOR_ID_REQUIRED", error: "creatorId is required" }); await requireAutomationCreatorAccess(req, creatorId); return res.json(await automationServer.listActivity({ agencyId: req.auth.agencyId, query: req.query || {} })); } catch (err) { return sendError(res, err, "AUTOMATION_ACTIVITY_FAILED"); } });
}

module.exports = { registerEventRoutes };
