const express = require("express");
const { z } = require("zod");

const prisma = require("../prisma");
const { authRequired } = require("../middleware/auth");
const { randomToken, sha256, addMinutes } = require("../utils/crypto");
const { encryptSnapshot, hashUserAgent } = require("../services/snapshot-crypto");
const { audit } = require("../services/audit-service");

const router = express.Router();

const startSchema = z.object({
  displayName: z.string().min(1).max(120),
  username: z.string().max(120).optional().nullable(),
  partition: z.string().max(220).optional().nullable(),
});

const claimSchema = z.object({
  token: z.string().min(20),
  deviceId: z.string().max(160).optional().nullable(),
  deviceName: z.string().max(160).optional().nullable(),
  platform: z.string().max(120).optional().nullable(),
  appVersion: z.string().max(80).optional().nullable(),
});

const completeSchema = z.object({
  token: z.string().min(20).optional(),
  deviceId: z.string().max(160).optional().nullable(),
  snapshot: z.object({
    cookies: z.array(z.any()).optional().default([]),
    userAgent: z.string().max(2000).optional().nullable(),
    storage: z.any().optional().nullable(),
    remoteId: z.string().max(120).optional().nullable(),
    username: z.string().max(120).optional().nullable(),
    displayName: z.string().max(120).optional().nullable(),
    avatarUrl: z.string().max(2000).optional().nullable(),
    capturedAt: z.string().optional().nullable(),
  }),
});

function validationError(res, err) {
  return res.status(400).json({
    ok: false,
    code: "VALIDATION_ERROR",
    error: err.issues?.[0]?.message || "Validation error",
    issues: err.issues || [],
  });
}

function appBaseUrl(req) {
  return (process.env.APP_URL || process.env.PUBLIC_BASE_URL || `${req.protocol}://${req.get("host")}`).replace(/\/+$/, "");
}

function makePartition(creatorId) {
  return `persist:creator_${creatorId}`;
}


// ---------------------------------------------------------------------------
// Public token endpoints for Electron deep-link flow.
//
// These endpoints DO NOT require Onlinod login inside Electron.
// Authorization is the one-time connect token generated by the authenticated
// web console in POST /api/creator-connect/start.
//
// Flow:
//   Web authenticated owner → /start → onlinod://connect?token=...
//   Electron receives token → /claim-public
//   Electron logs into OF → /complete-public
//
// The token is still hashed in DB and expires quickly.
// ---------------------------------------------------------------------------

async function findActiveSessionByToken(token) {
  const tokenHash = sha256(token);

  const session = await prisma.creatorConnectSession.findUnique({
    where: { tokenHash },
    include: {
      creator: true,
      createdByUser: true,
    },
  });

  if (!session) {
    return {
      ok: false,
      httpStatus: 404,
      code: "SESSION_NOT_FOUND",
      error: "Connect session not found",
    };
  }

  if (session.status !== "PENDING" && session.status !== "CLAIMED") {
    return {
      ok: false,
      httpStatus: 409,
      code: "SESSION_NOT_ACTIVE",
      error: `Session is ${session.status}`,
      session,
    };
  }

  if (session.expiresAt < new Date()) {
    await prisma.creatorConnectSession.update({
      where: { id: session.id },
      data: { status: "EXPIRED" },
    });

    return {
      ok: false,
      httpStatus: 410,
      code: "SESSION_EXPIRED",
      error: "Connect session expired",
      session,
    };
  }

  return {
    ok: true,
    session,
  };
}

async function upsertPublicDevice({ agencyId, userId, deviceId, deviceName, platform, appVersion }) {
  if (!deviceId && !deviceName && !platform && !appVersion) return null;

  const id = deviceId || `device_${userId}_${Date.now()}`;

  return prisma.workerDevice.upsert({
    where: { id },
    create: {
      id,
      agencyId,
      userId,
      deviceName: deviceName || null,
      platform: platform || null,
      appVersion: appVersion || null,
      lastSeenAt: new Date(),
    },
    update: {
      deviceName: deviceName || undefined,
      platform: platform || undefined,
      appVersion: appVersion || undefined,
      lastSeenAt: new Date(),
    },
  });
}

async function completeSessionWithSnapshot({ session, snapshot, deviceId, actorUserId, action }) {
  const snapshotPayload = {
    ...snapshot,
    creatorId: session.creatorId,
    agencyId: session.agencyId,
    capturedAt: snapshot.capturedAt || new Date().toISOString(),
  };

  const encrypted = encryptSnapshot(snapshotPayload);
  const username = snapshot.username || session.creator.username || null;
  const remoteId = snapshot.remoteId || session.creator.remoteId || null;

  const result = await prisma.$transaction(async (tx) => {
    await tx.accessSnapshot.updateMany({
      where: {
        agencyId: session.agencyId,
        creatorId: session.creatorId,
        active: true,
      },
      data: {
        active: false,
        revokedAt: new Date(),
      },
    });

    const accessSnapshot = await tx.accessSnapshot.create({
      data: {
        agencyId: session.agencyId,
        creatorId: session.creatorId,
        createdByUserId: actorUserId || session.createdByUserId,
        deviceId: deviceId || session.claimedByDeviceId || null,
        encryptedPayload: encrypted.encryptedPayload,
        iv: encrypted.iv,
        tag: encrypted.tag,
        algorithm: encrypted.algorithm,
        payloadVersion: encrypted.payloadVersion,
        userAgentHash: hashUserAgent(snapshot.userAgent),
        remoteId,
        username,
        active: true,
      },
    });

    const creator = await tx.creatorAccount.update({
      where: { id: session.creatorId },
      data: {
        status: "READY",
        username,
        remoteId,
        displayName: snapshot.displayName || session.creator.displayName,
        avatarUrl: snapshot.avatarUrl || session.creator.avatarUrl,
        partition: session.creator.partition || makePartition(session.creatorId),
      },
    });

    const updatedSession = await tx.creatorConnectSession.update({
      where: { id: session.id },
      data: {
        status: "COMPLETED",
        completedAt: new Date(),
        claimedByUserId: session.claimedByUserId || actorUserId || session.createdByUserId,
        claimedByDeviceId: session.claimedByDeviceId || deviceId || null,
        claimedAt: session.claimedAt || new Date(),
      },
    });

    return {
      accessSnapshot,
      creator,
      session: updatedSession,
    };
  });

  await audit({
    agencyId: session.agencyId,
    actorUserId: actorUserId || session.createdByUserId,
    action,
    targetType: "creator",
    targetId: result.creator.id,
    metadata: {
      sessionId: session.id,
      snapshotId: result.accessSnapshot.id,
      username,
      remoteId,
      deviceId: deviceId || session.claimedByDeviceId || null,
      cookiesCount: Array.isArray(snapshot.cookies) ? snapshot.cookies.length : 0,
    },
  });

  return result;
}

router.post("/claim-public", async (req, res) => {
  try {
    const input = claimSchema.parse(req.body);
    const found = await findActiveSessionByToken(input.token);

    if (!found.ok) {
      return res.status(found.httpStatus).json({
        ok: false,
        code: found.code,
        error: found.error,
      });
    }

    const session = found.session;

    const device = await upsertPublicDevice({
      agencyId: session.agencyId,
      userId: session.createdByUserId,
      deviceId: input.deviceId,
      deviceName: input.deviceName,
      platform: input.platform,
      appVersion: input.appVersion,
    });

    const updated = await prisma.creatorConnectSession.update({
      where: { id: session.id },
      data: {
        status: "CLAIMED",
        claimedByUserId: session.claimedByUserId || session.createdByUserId,
        claimedByDeviceId: device?.id || input.deviceId || null,
        claimedAt: session.claimedAt || new Date(),
      },
    });

    await audit({
      agencyId: session.agencyId,
      actorUserId: session.createdByUserId,
      action: "creator_connect.claim_public",
      targetType: "creator_connect_session",
      targetId: session.id,
      metadata: {
        creatorId: session.creatorId,
        deviceId: device?.id || input.deviceId || null,
      },
    });

    return res.json({
      ok: true,
      session: {
        id: updated.id,
        status: updated.status,
        expiresAt: updated.expiresAt,
      },
      creator: session.creator,
      agencyId: session.agencyId,
      partition: session.creator.partition || makePartition(session.creator.id),
      loginUrl: "https://onlyfans.com",
    });
  } catch (err) {
    if (err?.issues) return validationError(res, err);
    console.error("[creator-connect/claim-public] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "CONNECT_CLAIM_PUBLIC_FAILED",
      error: "Failed to claim creator connection",
    });
  }
});

router.get("/status-public", async (req, res) => {
  try {
    const token = String(req.query.token || "").trim();
    if (!token) {
      return res.status(400).json({
        ok: false,
        code: "TOKEN_MISSING",
        error: "Connect token is required",
      });
    }

    const tokenHash = sha256(token);
    const session = await prisma.creatorConnectSession.findUnique({
      where: { tokenHash },
      include: { creator: true },
    });

    if (!session) {
      return res.status(404).json({
        ok: false,
        code: "SESSION_NOT_FOUND",
        error: "Connect session not found",
      });
    }

    let status = session.status;
    if ((status === "PENDING" || status === "CLAIMED") && session.expiresAt < new Date()) {
      const updated = await prisma.creatorConnectSession.update({
        where: { id: session.id },
        data: { status: "EXPIRED" },
      });
      status = updated.status;
    }

    const latestSnapshot = await prisma.accessSnapshot.findFirst({
      where: {
        creatorId: session.creatorId,
        agencyId: session.agencyId,
        active: true,
      },
      orderBy: { createdAt: "desc" },
      select: {
        id: true,
        createdAt: true,
        username: true,
        remoteId: true,
        active: true,
      },
    });

    return res.json({
      ok: true,
      session: {
        id: session.id,
        status,
        expiresAt: session.expiresAt,
        claimedAt: session.claimedAt,
        completedAt: session.completedAt,
      },
      creator: session.creator,
      latestSnapshot,
    });
  } catch (err) {
    console.error("[creator-connect/status-public] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "CONNECT_STATUS_PUBLIC_FAILED",
      error: "Failed to read creator connection status",
    });
  }
});

router.post("/complete-public", async (req, res) => {
  try {
    const input = completeSchema.extend({
      token: z.string().min(20),
    }).parse(req.body);

    const found = await findActiveSessionByToken(input.token);

    if (!found.ok) {
      return res.status(found.httpStatus).json({
        ok: false,
        code: found.code,
        error: found.error,
      });
    }

    const session = found.session;

    const result = await completeSessionWithSnapshot({
      session,
      snapshot: input.snapshot,
      deviceId: input.deviceId || session.claimedByDeviceId || null,
      actorUserId: session.createdByUserId,
      action: "creator_connect.complete_public",
    });

    return res.json({
      ok: true,
      session: {
        id: result.session.id,
        status: result.session.status,
        completedAt: result.session.completedAt,
      },
      creator: result.creator,
      snapshot: {
        id: result.accessSnapshot.id,
        active: result.accessSnapshot.active,
        createdAt: result.accessSnapshot.createdAt,
        username: result.accessSnapshot.username,
        remoteId: result.accessSnapshot.remoteId,
      },
    });
  } catch (err) {
    if (err?.issues) return validationError(res, err);
    console.error("[creator-connect/complete-public] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "CONNECT_COMPLETE_PUBLIC_FAILED",
      error: err?.message || "Failed to complete creator connection",
    });
  }
});

router.post("/simulate-complete-public", async (req, res) => {
  try {
    const token = String(req.body?.token || "").trim();
    if (!token) {
      return res.status(400).json({
        ok: false,
        code: "TOKEN_MISSING",
        error: "Connect token is required",
      });
    }

    const found = await findActiveSessionByToken(token);

    if (!found.ok) {
      return res.status(found.httpStatus).json({
        ok: false,
        code: found.code,
        error: found.error,
      });
    }

    const session = found.session;

    const snapshot = {
      cookies: [
        {
          name: "dev_session",
          value: `dev_${Date.now()}`,
          domain: ".onlyfans.com",
          path: "/",
          secure: true,
          httpOnly: true,
        },
      ],
      userAgent: req.headers["user-agent"] || "Onlinod Public Dev",
      remoteId: session.creator.remoteId || `remote_${Date.now()}`,
      username: session.creator.username || `creator_${Date.now()}`,
      displayName: session.creator.displayName || "Creator",
      avatarUrl: session.creator.avatarUrl || null,
      capturedAt: new Date().toISOString(),
    };

    const result = await completeSessionWithSnapshot({
      session,
      snapshot,
      deviceId: "public-web-dev-simulator",
      actorUserId: session.createdByUserId,
      action: "creator_connect.simulate_complete_public",
    });

    return res.json({
      ok: true,
      creator: result.creator,
      session: {
        id: result.session.id,
        status: result.session.status,
        completedAt: result.session.completedAt,
      },
      snapshot: {
        id: result.accessSnapshot.id,
        active: result.accessSnapshot.active,
        createdAt: result.accessSnapshot.createdAt,
      },
    });
  } catch (err) {
    console.error("[creator-connect/simulate-complete-public] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "SIMULATE_COMPLETE_PUBLIC_FAILED",
      error: err?.message || "Failed to simulate complete",
    });
  }
});


router.use(authRequired);

router.post("/start", async (req, res) => {
  try {
    const input = startSchema.parse(req.body);
    const token = randomToken(32);

    const result = await prisma.$transaction(async (tx) => {
      const creator = await tx.creatorAccount.create({
        data: {
          agencyId: req.auth.agencyId,
          displayName: input.displayName,
          username: input.username || null,
          status: "DRAFT",
          partition: input.partition || null,
        },
      });

      const partition = input.partition || makePartition(creator.id);

      const updatedCreator = await tx.creatorAccount.update({
        where: { id: creator.id },
        data: { partition },
      });

      const session = await tx.creatorConnectSession.create({
        data: {
          agencyId: req.auth.agencyId,
          creatorId: creator.id,
          createdByUserId: req.auth.userId,
          tokenHash: sha256(token),
          status: "PENDING",
          expiresAt: addMinutes(10),
        },
      });

      return {
        creator: updatedCreator,
        session,
      };
    });

    const connectUrl = `onlinod://connect?token=${encodeURIComponent(token)}`;

    await prisma.creatorConnectSession.update({
      where: { id: result.session.id },
      data: { connectUrl },
    });

    await audit({
      agencyId: req.auth.agencyId,
      actorUserId: req.auth.userId,
      action: "creator_connect.start",
      targetType: "creator",
      targetId: result.creator.id,
      metadata: {
        sessionId: result.session.id,
        username: result.creator.username,
      },
    });

    return res.status(201).json({
      ok: true,
      creator: result.creator,
      session: {
        id: result.session.id,
        status: result.session.status,
        expiresAt: result.session.expiresAt,
      },
      connectUrl,
      token,
      browserFallbackUrl: `${appBaseUrl(req)}/?connectSession=${encodeURIComponent(result.session.id)}`,
    });
  } catch (err) {
    if (err?.issues) return validationError(res, err);
    console.error("[creator-connect/start] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "CONNECT_START_FAILED",
      error: "Failed to start creator connection",
    });
  }
});

router.post("/claim", async (req, res) => {
  try {
    const input = claimSchema.parse(req.body);
    const tokenHash = sha256(input.token);

    const session = await prisma.creatorConnectSession.findUnique({
      where: { tokenHash },
      include: { creator: true },
    });

    if (!session) {
      return res.status(404).json({ ok: false, code: "SESSION_NOT_FOUND", error: "Connect session not found" });
    }

    if (session.agencyId !== req.auth.agencyId) {
      return res.status(403).json({ ok: false, code: "FORBIDDEN", error: "Connect session belongs to another agency" });
    }

    if (session.status !== "PENDING" && session.status !== "CLAIMED") {
      return res.status(409).json({ ok: false, code: "SESSION_NOT_PENDING", error: `Session is ${session.status}` });
    }

    if (session.expiresAt < new Date()) {
      await prisma.creatorConnectSession.update({
        where: { id: session.id },
        data: { status: "EXPIRED" },
      });

      return res.status(410).json({ ok: false, code: "SESSION_EXPIRED", error: "Connect session expired" });
    }

    let device = null;
    if (input.deviceId || input.deviceName || input.platform || input.appVersion) {
      device = await prisma.workerDevice.upsert({
        where: { id: input.deviceId || `device_${req.auth.userId}_${Date.now()}` },
        create: {
          id: input.deviceId || undefined,
          agencyId: req.auth.agencyId,
          userId: req.auth.userId,
          deviceName: input.deviceName || null,
          platform: input.platform || null,
          appVersion: input.appVersion || null,
          lastSeenAt: new Date(),
        },
        update: {
          deviceName: input.deviceName || undefined,
          platform: input.platform || undefined,
          appVersion: input.appVersion || undefined,
          lastSeenAt: new Date(),
        },
      });
    }

    const updated = await prisma.creatorConnectSession.update({
      where: { id: session.id },
      data: {
        status: "CLAIMED",
        claimedByUserId: req.auth.userId,
        claimedByDeviceId: device?.id || input.deviceId || null,
        claimedAt: session.claimedAt || new Date(),
      },
    });

    await audit({
      agencyId: req.auth.agencyId,
      actorUserId: req.auth.userId,
      action: "creator_connect.claim",
      targetType: "creator_connect_session",
      targetId: session.id,
      metadata: { creatorId: session.creatorId, deviceId: device?.id || input.deviceId || null },
    });

    return res.json({
      ok: true,
      session: {
        id: updated.id,
        status: updated.status,
        expiresAt: updated.expiresAt,
      },
      creator: session.creator,
      partition: session.creator.partition || makePartition(session.creator.id),
      loginUrl: "https://onlyfans.com",
    });
  } catch (err) {
    if (err?.issues) return validationError(res, err);
    console.error("[creator-connect/claim] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "CONNECT_CLAIM_FAILED",
      error: "Failed to claim creator connection",
    });
  }
});

router.get("/:id/status", async (req, res) => {
  try {
    const session = await prisma.creatorConnectSession.findFirst({
      where: {
        id: req.params.id,
        agencyId: req.auth.agencyId,
      },
      include: {
        creator: true,
      },
    });

    if (!session) {
      return res.status(404).json({ ok: false, code: "SESSION_NOT_FOUND", error: "Connect session not found" });
    }

    let status = session.status;
    if ((status === "PENDING" || status === "CLAIMED") && session.expiresAt < new Date()) {
      const updated = await prisma.creatorConnectSession.update({
        where: { id: session.id },
        data: { status: "EXPIRED" },
      });
      status = updated.status;
    }

    const latestSnapshot = await prisma.accessSnapshot.findFirst({
      where: {
        creatorId: session.creatorId,
        agencyId: req.auth.agencyId,
        active: true,
      },
      orderBy: { createdAt: "desc" },
      select: {
        id: true,
        createdAt: true,
        username: true,
        remoteId: true,
        active: true,
      },
    });

    return res.json({
      ok: true,
      session: {
        id: session.id,
        status,
        expiresAt: session.expiresAt,
        claimedAt: session.claimedAt,
        completedAt: session.completedAt,
      },
      creator: session.creator,
      latestSnapshot,
    });
  } catch (err) {
    console.error("[creator-connect/status] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "CONNECT_STATUS_FAILED",
      error: "Failed to read creator connection status",
    });
  }
});

router.post("/:id/complete", async (req, res) => {
  try {
    const input = completeSchema.parse(req.body);

    const session = await prisma.creatorConnectSession.findFirst({
      where: {
        id: req.params.id,
        agencyId: req.auth.agencyId,
      },
      include: {
        creator: true,
      },
    });

    if (!session) {
      return res.status(404).json({ ok: false, code: "SESSION_NOT_FOUND", error: "Connect session not found" });
    }

    if (session.status !== "PENDING" && session.status !== "CLAIMED") {
      return res.status(409).json({ ok: false, code: "SESSION_NOT_ACTIVE", error: `Session is ${session.status}` });
    }

    if (session.expiresAt < new Date()) {
      await prisma.creatorConnectSession.update({
        where: { id: session.id },
        data: { status: "EXPIRED" },
      });
      return res.status(410).json({ ok: false, code: "SESSION_EXPIRED", error: "Connect session expired" });
    }

    if (input.token && sha256(input.token) !== session.tokenHash) {
      return res.status(403).json({ ok: false, code: "TOKEN_INVALID", error: "Connect token is invalid" });
    }

    const snapshotPayload = {
      ...input.snapshot,
      creatorId: session.creatorId,
      agencyId: req.auth.agencyId,
      capturedAt: input.snapshot.capturedAt || new Date().toISOString(),
    };

    const encrypted = encryptSnapshot(snapshotPayload);
    const username = input.snapshot.username || session.creator.username || null;
    const remoteId = input.snapshot.remoteId || session.creator.remoteId || null;

    const result = await prisma.$transaction(async (tx) => {
      await tx.accessSnapshot.updateMany({
        where: {
          agencyId: req.auth.agencyId,
          creatorId: session.creatorId,
          active: true,
        },
        data: {
          active: false,
          revokedAt: new Date(),
        },
      });

      const accessSnapshot = await tx.accessSnapshot.create({
        data: {
          agencyId: req.auth.agencyId,
          creatorId: session.creatorId,
          createdByUserId: req.auth.userId,
          deviceId: input.deviceId || session.claimedByDeviceId || null,
          encryptedPayload: encrypted.encryptedPayload,
          iv: encrypted.iv,
          tag: encrypted.tag,
          algorithm: encrypted.algorithm,
          payloadVersion: encrypted.payloadVersion,
          userAgentHash: hashUserAgent(input.snapshot.userAgent),
          remoteId,
          username,
          active: true,
        },
      });

      const creator = await tx.creatorAccount.update({
        where: { id: session.creatorId },
        data: {
          status: "READY",
          username,
          remoteId,
          displayName: input.snapshot.displayName || session.creator.displayName,
          avatarUrl: input.snapshot.avatarUrl || session.creator.avatarUrl,
          partition: session.creator.partition || makePartition(session.creatorId),
        },
      });

      const updatedSession = await tx.creatorConnectSession.update({
        where: { id: session.id },
        data: {
          status: "COMPLETED",
          completedAt: new Date(),
          claimedByUserId: session.claimedByUserId || req.auth.userId,
          claimedByDeviceId: session.claimedByDeviceId || input.deviceId || null,
        },
      });

      return {
        accessSnapshot,
        creator,
        session: updatedSession,
      };
    });

    await audit({
      agencyId: req.auth.agencyId,
      actorUserId: req.auth.userId,
      action: "creator_connect.complete",
      targetType: "creator",
      targetId: result.creator.id,
      metadata: {
        sessionId: session.id,
        snapshotId: result.accessSnapshot.id,
        username,
        remoteId,
        cookiesCount: Array.isArray(input.snapshot.cookies) ? input.snapshot.cookies.length : 0,
      },
    });

    return res.json({
      ok: true,
      session: {
        id: result.session.id,
        status: result.session.status,
        completedAt: result.session.completedAt,
      },
      creator: result.creator,
      snapshot: {
        id: result.accessSnapshot.id,
        active: result.accessSnapshot.active,
        createdAt: result.accessSnapshot.createdAt,
        username: result.accessSnapshot.username,
        remoteId: result.accessSnapshot.remoteId,
      },
    });
  } catch (err) {
    if (err?.issues) return validationError(res, err);
    console.error("[creator-connect/complete] failed:", err);

    return res.status(500).json({
      ok: false,
      code: "CONNECT_COMPLETE_FAILED",
      error: err?.message || "Failed to complete creator connection",
    });
  }
});

router.post("/:id/simulate-complete", async (req, res) => {
  try {
    const session = await prisma.creatorConnectSession.findFirst({
      where: {
        id: req.params.id,
        agencyId: req.auth.agencyId,
      },
      include: { creator: true },
    });

    if (!session) {
      return res.status(404).json({ ok: false, code: "SESSION_NOT_FOUND", error: "Connect session not found" });
    }

    req.body = {
      snapshot: {
        cookies: [
          {
            name: "dev_session",
            value: `dev_${Date.now()}`,
            domain: ".onlyfans.com",
            path: "/",
            secure: true,
            httpOnly: true,
          },
        ],
        userAgent: req.headers["user-agent"] || "Onlinod Dev",
        remoteId: session.creator.remoteId || `remote_${Date.now()}`,
        username: session.creator.username || `creator_${Date.now()}`,
        displayName: session.creator.displayName || "Creator",
        avatarUrl: session.creator.avatarUrl || null,
        capturedAt: new Date().toISOString(),
      },
    };

    // Reuse the same logic by calling local helper would be cleaner, but
    // Express cannot re-enter the route stack safely. Keep the operation explicit.
    const encrypted = encryptSnapshot({
      ...req.body.snapshot,
      creatorId: session.creatorId,
      agencyId: req.auth.agencyId,
    });

    const username = req.body.snapshot.username;
    const remoteId = req.body.snapshot.remoteId;

    const result = await prisma.$transaction(async (tx) => {
      await tx.accessSnapshot.updateMany({
        where: {
          agencyId: req.auth.agencyId,
          creatorId: session.creatorId,
          active: true,
        },
        data: {
          active: false,
          revokedAt: new Date(),
        },
      });

      const accessSnapshot = await tx.accessSnapshot.create({
        data: {
          agencyId: req.auth.agencyId,
          creatorId: session.creatorId,
          createdByUserId: req.auth.userId,
          deviceId: "web-dev-simulator",
          encryptedPayload: encrypted.encryptedPayload,
          iv: encrypted.iv,
          tag: encrypted.tag,
          algorithm: encrypted.algorithm,
          payloadVersion: encrypted.payloadVersion,
          userAgentHash: hashUserAgent(req.body.snapshot.userAgent),
          remoteId,
          username,
          active: true,
        },
      });

      const creator = await tx.creatorAccount.update({
        where: { id: session.creatorId },
        data: {
          status: "READY",
          username,
          remoteId,
          displayName: req.body.snapshot.displayName,
          avatarUrl: req.body.snapshot.avatarUrl,
          partition: session.creator.partition || makePartition(session.creatorId),
        },
      });

      const updatedSession = await tx.creatorConnectSession.update({
        where: { id: session.id },
        data: {
          status: "COMPLETED",
          completedAt: new Date(),
          claimedByDeviceId: session.claimedByDeviceId || "web-dev-simulator",
          claimedByUserId: session.claimedByUserId || req.auth.userId,
          claimedAt: session.claimedAt || new Date(),
        },
      });

      return {
        accessSnapshot,
        creator,
        session: updatedSession,
      };
    });

    await audit({
      agencyId: req.auth.agencyId,
      actorUserId: req.auth.userId,
      action: "creator_connect.simulate_complete",
      targetType: "creator",
      targetId: result.creator.id,
      metadata: {
        sessionId: session.id,
        snapshotId: result.accessSnapshot.id,
      },
    });

    return res.json({
      ok: true,
      creator: result.creator,
      session: {
        id: result.session.id,
        status: result.session.status,
        completedAt: result.session.completedAt,
      },
      snapshot: {
        id: result.accessSnapshot.id,
        active: result.accessSnapshot.active,
        createdAt: result.accessSnapshot.createdAt,
      },
    });
  } catch (err) {
    console.error("[creator-connect/simulate-complete] failed:", err);
    return res.status(500).json({
      ok: false,
      code: "SIMULATE_COMPLETE_FAILED",
      error: err?.message || "Failed to simulate complete",
    });
  }
});

module.exports = router;
